# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e845397bea5e5fcb15a75683735f8c04d519d4df054d841d0745b94bc513a35c366a242233a8012b4eef7de9f7c991512531df32a8b098e8a6814c60c4d4d9f1

test:
  secret_key_base: 3ebd1ab0ed62dc77cbfc2a6dcbc2d4c60acfaf36bac8491c3ed00c96accdff3c4b2f95410875098387451601ef239d7b472d07eaccba494c354d4cd17bda8caf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
